// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Paradox Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Paradox.VisualStudio.Package .vsix
// and re-save the associated .pdxfx.
// </auto-generated>

using System;
using SiliconStudio.Core;
using SiliconStudio.Paradox.Rendering;
using SiliconStudio.Paradox.Graphics;
using SiliconStudio.Paradox.Shaders;
using SiliconStudio.Core.Mathematics;
using Buffer = SiliconStudio.Paradox.Graphics.Buffer;

namespace SiliconStudio.Paradox.Graphics.Tests
{
    internal static partial class ShaderMixins
    {
        internal partial class CustomSubEffect  : IShaderMixinBuilder
        {
            public void Generate(ShaderMixinSource mixin, ShaderMixinContext context)
            {
                if (context.GetParam(CustomShaderKeys.SwitchEffectLevel) < 10)
                {
                    context.Mixin(mixin, "CustomShader");
                }
                else
                {
                    context.Mixin(mixin, "CustomShader2");
                }
            }

            [ModuleInitializer]
            internal static void __Initialize__()

            {
                ShaderMixinManager.Register("CustomSubEffect", new CustomSubEffect());
            }
        }
    }
    internal static partial class ShaderMixins
    {
        internal partial class CustomEffect  : IShaderMixinBuilder
        {
            public void Generate(ShaderMixinSource mixin, ShaderMixinContext context)
            {
                context.Mixin(mixin, "CustomShader");
                if (context.ChildEffectName == "CustomSubEffect")
                {
                    context.Mixin(mixin, "CustomSubEffect");
                    return;
                }
            }

            [ModuleInitializer]
            internal static void __Initialize__()

            {
                ShaderMixinManager.Register("CustomEffect", new CustomEffect());
            }
        }
    }
}
