// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Paradox Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Paradox.VisualStudio.Package .vsix
// and re-save the associated .pdxfx.
// </auto-generated>

using System;
using SiliconStudio.Core;
using SiliconStudio.Paradox.Rendering;
using SiliconStudio.Paradox.Graphics;
using SiliconStudio.Paradox.Shaders;
using SiliconStudio.Core.Mathematics;
using Buffer = SiliconStudio.Paradox.Graphics.Buffer;

namespace SiliconStudio.Paradox.Rendering.Images
{
    internal static partial class VignettingShaderKeys
    {
        public static readonly ParameterKey<float> Amount = ParameterKeys.New<float>();
        public static readonly ParameterKey<float> RadiusBegin = ParameterKeys.New<float>();
        public static readonly ParameterKey<Color3> Color = ParameterKeys.New<Color3>();
    }
}
