// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Paradox Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Paradox.VisualStudio.Package .vsix
// and re-save the associated .pdxfx.
// </auto-generated>

using System;
using SiliconStudio.Core;
using SiliconStudio.Paradox.Effects;
using SiliconStudio.Paradox.Graphics;
using SiliconStudio.Paradox.Shaders;
using SiliconStudio.Core.Mathematics;
using Buffer = SiliconStudio.Paradox.Graphics.Buffer;

namespace SiliconStudio.Paradox.Effects
{
    public static partial class PhysicsDebugEffectKeys
    {
        public static readonly ParameterKey<Matrix> WorldViewProj = ParameterKeys.New<Matrix>();
        public static readonly ParameterKey<Color4> Color = ParameterKeys.New<Color4>(new Color4(1,1,1,1));
        public static readonly ParameterKey<float> UseUv = ParameterKeys.New<float>(1.0f);
    }
}
