// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Paradox Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Paradox.VisualStudio.Package .vsix
// and re-save the associated .pdxfx.
// </auto-generated>

using System;
using SiliconStudio.Core;
using SiliconStudio.Paradox.Effects;
using SiliconStudio.Paradox.Graphics;
using SiliconStudio.Paradox.Shaders;
using SiliconStudio.Core.Mathematics;
using Buffer = SiliconStudio.Paradox.Graphics.Buffer;

namespace SiliconStudio.Paradox.Effects.Images
{
    internal static partial class ToneMapU2FilmicOperatorShaderKeys
    {
        public static readonly ParameterKey<float> ShoulderStrength = ParameterKeys.New<float>(0.22f);
        public static readonly ParameterKey<float> LinearStrength = ParameterKeys.New<float>(0.25f);
        public static readonly ParameterKey<float> LinearAngle = ParameterKeys.New<float>(0.1f);
        public static readonly ParameterKey<float> ToeStrength = ParameterKeys.New<float>(0.2f);
        public static readonly ParameterKey<float> ToeNumerator = ParameterKeys.New<float>(0.01f);
        public static readonly ParameterKey<float> ToeDenominator = ParameterKeys.New<float>(0.3f);
        public static readonly ParameterKey<float> LinearWhite = ParameterKeys.New<float>(11.2f);
    }
}
