// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Paradox Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Paradox.VisualStudio.Package .vsix
// and re-save the associated .pdxfx.
// </auto-generated>

using System;
using SiliconStudio.Core;
using SiliconStudio.Paradox.Rendering;
using SiliconStudio.Paradox.Graphics;
using SiliconStudio.Paradox.Shaders;
using SiliconStudio.Core.Mathematics;
using Buffer = SiliconStudio.Paradox.Graphics.Buffer;

namespace SiliconStudio.Paradox.Rendering.Lights
{
    public static partial class LightSpotGroupKeys
    {
        public static readonly ParameterKey<Vector3[]> LightPositionWS = ParameterKeys.New<Vector3[]>();
        public static readonly ParameterKey<Vector3[]> LightDirectionsWS = ParameterKeys.New<Vector3[]>();
        public static readonly ParameterKey<Vector3[]> LightAngleOffsetAndInvSquareRadius = ParameterKeys.New<Vector3[]>();
        public static readonly ParameterKey<Color3[]> LightColor = ParameterKeys.New<Color3[]>();
    }
}
