// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Paradox Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Paradox.VisualStudio.Package .vsix
// and re-save the associated .pdxfx.
// </auto-generated>

using System;
using SiliconStudio.Core;
using SiliconStudio.Paradox.Rendering;
using SiliconStudio.Paradox.Graphics;
using SiliconStudio.Paradox.Shaders;
using SiliconStudio.Core.Mathematics;
using Buffer = SiliconStudio.Paradox.Graphics.Buffer;

namespace SiliconStudio.Paradox.Rendering.Images
{
    public static partial class DepthMinMaxShaderKeys
    {
        public static readonly ParameterKey<Texture> TextureMap = ParameterKeys.New<Texture>();
        public static readonly ParameterKey<Texture> TextureReduction = ParameterKeys.New<Texture>();
    }
}
