// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Paradox Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Paradox.VisualStudio.Package .vsix
// and re-save the associated .pdxfx.
// </auto-generated>

using System;
using SiliconStudio.Core;
using SiliconStudio.Paradox.Effects;
using SiliconStudio.Paradox.Graphics;
using SiliconStudio.Paradox.Shaders;
using SiliconStudio.Core.Mathematics;
using Buffer = SiliconStudio.Paradox.Graphics.Buffer;


#line 3 "D:\Code\Paradox\sources\engine\SiliconStudio.Paradox.Shaders.Tests\GameAssets\Mixins\test_mixin_simple_compose.pdxfx"
namespace Test6
{

    #line 5
    internal static partial class ShaderMixins
    {
        internal partial class DefaultSimpleCompose  : IShaderMixinBuilder
        {
            public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
            {

                #line 7
                context.Mixin(mixin, "A");

                #line 8
                context.Mixin(mixin, "B");

                #line 9
                context.Mixin(mixin, "C");

                {

                    #line 10
                    var __subMixin = new ShaderMixinSourceTree() { Parent = mixin };

                    #line 10
                    context.Mixin(__subMixin, "X");
                    mixin.Mixin.AddComposition("x", __subMixin.Mixin);
                }
            }

            [ModuleInitializer]
            internal static void __Initialize__()

            {
                ShaderMixinManager.Register("DefaultSimpleCompose", new DefaultSimpleCompose());
            }
        }
    }
}
