// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Paradox Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Paradox.VisualStudio.Package .vsix
// and re-save the associated .pdxfx.
// </auto-generated>

using System;
using SiliconStudio.Core;
using SiliconStudio.Paradox.Effects;
using SiliconStudio.Paradox.Graphics;
using SiliconStudio.Paradox.Shaders;
using SiliconStudio.Core.Mathematics;
using Buffer = SiliconStudio.Paradox.Graphics.Buffer;

namespace SiliconStudio.Paradox.Effects
{
    [DataContract]public partial class RenderingParameters : ShaderMixinParameters
    {
        public static readonly ParameterKey<bool> UseDeferred = ParameterKeys.New<bool>();
        public static readonly ParameterKey<bool> UseTransparent = ParameterKeys.New<bool>();
        public static readonly ParameterKey<RenderLayers> RenderLayer = ParameterKeys.New<RenderLayers>(RenderLayers.RenderLayerAll);
        public static readonly ParameterKey<RenderLayers> ActiveRenderLayer = ParameterKeys.New<RenderLayers>(RenderLayers.RenderLayerAll);
    };
}
