// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Paradox Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Paradox.VisualStudio.Package .vsix
// and re-save the associated .pdxfx.
// </auto-generated>

using SiliconStudio.Core;
using SiliconStudio.Paradox.Effects;
using SiliconStudio.Paradox.Shaders;


#line 1 "E:\Code\Paradox\sources\engine\SiliconStudio.Paradox.Engine\Effects\RenderingParameters.pdxfx"
namespace SiliconStudio.Paradox.Effects
{

    #line 3
    public partial class RenderingParameters : ShaderMixinParameters
    {

        #line 5
        public static readonly ParameterKey<bool> UseDeferred = ParameterKeys.New<bool>();

        #line 6
        public static readonly ParameterKey<bool> UseTransparent = ParameterKeys.New<bool>();
    };
}
