// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Paradox Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Paradox.VisualStudio.Package .vsix
// and re-save the associated .pdxfx.
// </auto-generated>

using System;
using SiliconStudio.Core;
using SiliconStudio.Paradox.Effects;
using SiliconStudio.Paradox.Graphics;
using SiliconStudio.Paradox.Shaders;
using SiliconStudio.Core.Mathematics;
using Buffer = SiliconStudio.Paradox.Graphics.Buffer;

namespace SiliconStudio.Paradox.Effects.Images
{
    internal static partial class ToneMapShaderKeys
    {
        public static readonly ParameterKey<float> KeyValue = ParameterKeys.New<float>();
        public static readonly ParameterKey<bool> AutoKeyValue = ParameterKeys.New<bool>();
        public static readonly ParameterKey<float> LuminanceLocalFactor = ParameterKeys.New<float>();
        public static readonly ParameterKey<float> LuminanceAverageGlobal = ParameterKeys.New<float>();
        public static readonly ParameterKey<float> LinearWhite = ParameterKeys.New<float>();
        public static readonly ParameterKey<float> Gamma = ParameterKeys.New<float>();
        public static readonly ParameterKey<float> Contrast = ParameterKeys.New<float>();
        public static readonly ParameterKey<float> Brightness = ParameterKeys.New<float>();
    }
}
