// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Paradox Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Paradox.VisualStudio.Package .vsix
// and re-save the associated .pdxfx.
// </auto-generated>

using System;
using SiliconStudio.Core;
using SiliconStudio.Paradox.Rendering;
using SiliconStudio.Paradox.Graphics;
using SiliconStudio.Paradox.Shaders;
using SiliconStudio.Core.Mathematics;
using Buffer = SiliconStudio.Paradox.Graphics.Buffer;

namespace SiliconStudio.Paradox.Rendering
{
    public static partial class ComputeColorTextureDynamicScaledOffsetKeys
    {
        public static readonly ParameterKey<Vector2> Offset = ParameterKeys.New<Vector2>(new Vector2(0,0));
        public static readonly ParameterKey<Vector2> Scale = ParameterKeys.New<Vector2>(new Vector2(1,1));
    }
}
