// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Paradox Data Code Generator.
// To generate it yourself, please install SiliconStudio.Paradox.VisualStudio.Package .vsix
// and re-save the associated .pdxdata.
// </auto-generated>

namespace SiliconStudio.Paradox.Data
{
    /// <summary>
    /// Module initializer for data types of assembly SiliconStudio.Paradox.
    /// </summary>
    class DataInitializer
    {
        [SiliconStudio.Core.ModuleInitializer]
        internal static void Initialize()
        {
            // Register type ParameterCollectionData
            SiliconStudio.Core.Serialization.Converters.ConverterContext.RegisterConverter(new SiliconStudio.Paradox.Effects.Data.ParameterCollectionDataConverter());
        }
    }
}

namespace SiliconStudio.Paradox.Effects.Data
{
    /// <summary>
    /// Data type for <see cref="SiliconStudio.Paradox.Effects.ParameterCollection"/>.
    /// </summary>
    [SiliconStudio.Core.DataContract("ParameterCollectionData")]
    public partial class ParameterCollectionData
    {
    }




}

