// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using SiliconStudio.Core;
using SiliconStudio.Xenko.Rendering;
using SiliconStudio.Xenko.Graphics;
using SiliconStudio.Xenko.Shaders;
using SiliconStudio.Core.Mathematics;
using Buffer = SiliconStudio.Xenko.Graphics.Buffer;

namespace SiliconStudio.Xenko.Rendering.Utils
{
    public static partial class ModelComponentPickingShaderKeys
    {
        public static readonly ValueParameterKey<Color4> ModelComponentId = ParameterKeys.NewValue<Color4>();
        public static readonly ValueParameterKey<Color4> MeshId = ParameterKeys.NewValue<Color4>();
        public static readonly ValueParameterKey<Color4> MaterialId = ParameterKeys.NewValue<Color4>();
    }
}
