// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Paradox Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Paradox.VisualStudio.Package .vsix
// and re-save the associated .pdxfx.
// </auto-generated>

using System;
using SiliconStudio.Core;
using SiliconStudio.Paradox.Effects;
using SiliconStudio.Paradox.Graphics;
using SiliconStudio.Paradox.Shaders;
using SiliconStudio.Core.Mathematics;
using Buffer = SiliconStudio.Paradox.Graphics.Buffer;

namespace SiliconStudio.Paradox.Effects.Modules
{
    public static partial class ComputeColorTextureCubeParallaxKeys
    {
        public static readonly ParameterKey<float> CubemapRange = ParameterKeys.New<float>(1);
        public static readonly ParameterKey<Vector3> CubemapCenterWS = ParameterKeys.New<Vector3>(new Vector3(0,0,0));
    }
}
