// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Paradox Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Paradox.VisualStudio.Package .vsix
// and re-save the associated .pdxfx.
// </auto-generated>

using System;
using SiliconStudio.Core;
using SiliconStudio.Paradox.Effects;
using SiliconStudio.Paradox.Graphics;
using SiliconStudio.Paradox.Shaders;
using SiliconStudio.Core.Mathematics;
using Buffer = SiliconStudio.Paradox.Graphics.Buffer;


#line 3 "C:\Code\Paradox\sources\shaders\Cubemap\CubemapIBLBase.pdxsl"
namespace SiliconStudio.Paradox.Effects.Cubemap
{
    public static partial class CubemapIBLBaseKeys
    {
        public static readonly ParameterKey<float> CubemapRadius = ParameterKeys.New<float>();
        public static readonly ParameterKey<Vector3> CubemapPosition = ParameterKeys.New<Vector3>();
        public static readonly ParameterKey<Texture> Cubemap = ParameterKeys.New<Texture>();
    }
}
