// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Paradox Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Paradox.VisualStudio.Package .vsix
// and re-save the associated .pdxfx.
// </auto-generated>

using SiliconStudio.Core;
using SiliconStudio.Paradox.Effects;
using SiliconStudio.Paradox.Shaders;
using SiliconStudio.Core.Mathematics;
using SiliconStudio.Paradox.Graphics;


#line 1 "C:\Projects\Paradox\sources\shaders\BasicShaders.pdxfx"
using SiliconStudio.Paradox.Effects.Data;

#line 2
using SiliconStudio.Paradox.Effects.Modules;

#line 4
namespace BasicShaders
{
    [DataContract]
#line 6
    public partial class BasicShadersParameters : ShaderMixinParameters
    {

        #line 8
        public static readonly ParameterKey<bool> UsedNormalMap = ParameterKeys.New<bool>(false);
    };

    #line 14
    public partial class ParadoxTessellation  : IShaderMixinBuilder
    {
        public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
        {
        }

        [ModuleInitializer]
        internal static void __Initialize__()

        {
            ShaderMixinManager.Register("ParadoxTessellation", new ParadoxTessellation());
        }
    }

    #line 28
    public partial class ParadoxSkinning  : IShaderMixinBuilder
    {
        public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
        {

            #line 33
            if (context.GetParam(MaterialParameters.HasSkinningPosition))
            {

                #line 35
                if (context.GetParam(MaterialParameters.SkinningBones) > context.GetParam(MaterialParameters.SkinningMaxBones))
                {

                    #line 38
                    context.SetParam(MaterialParameters.SkinningMaxBones, context.GetParam(MaterialParameters.SkinningBones));
                }

                #line 40
                mixin.Mixin.AddMacro("SkinningMaxBones", context.GetParam(MaterialParameters.SkinningMaxBones));

                #line 41
                context.Mixin(mixin, "TransformationSkinning");

                #line 43
                if (context.GetParam(MaterialParameters.HasSkinningNormal))
                {

                    #line 45
                    if (context.GetParam(BasicShadersParameters.UsedNormalMap))

                        #line 46
                        context.Mixin(mixin, "TangentToViewSkinning");

                    #line 48
                    else

                        #line 48
                        context.Mixin(mixin, "NormalVSSkinning");

                    #line 50
                    context.Mixin(mixin, "NormalSkinning");
                }

                #line 53
                if (context.GetParam(MaterialParameters.HasSkinningTangent))

                    #line 54
                    context.Mixin(mixin, "TangentSkinning");
            }
        }

        [ModuleInitializer]
        internal static void __Initialize__()

        {
            ShaderMixinManager.Register("ParadoxSkinning", new ParadoxSkinning());
        }
    }

    #line 61
    public partial class ParadoxShadowCast  : IShaderMixinBuilder
    {
        public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
        {

            #line 66
            if (context.GetParam(LightingKeys.CastShadows))

                {

                    #line 67
                    var __subMixin = new ShaderMixinSourceTree() { Name = "ShadowMapCaster", Parent = mixin };
                    mixin.Children.Add(__subMixin);

                    #line 67
                    context.BeginChild(__subMixin);

                    #line 67
                    context.Mixin(__subMixin, "ShadowMapCaster");

                    #line 67
                    context.EndChild();
                }
        }

        [ModuleInitializer]
        internal static void __Initialize__()

        {
            ShaderMixinManager.Register("ParadoxShadowCast", new ParadoxShadowCast());
        }
    }

    #line 73
    public partial class ParadoxBaseShader  : IShaderMixinBuilder
    {
        public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
        {

            #line 78
            context.Mixin(mixin, "ShaderBase");

            #line 79
            context.Mixin(mixin, "ShadingBase");

            #line 80
            context.Mixin(mixin, "TransformationWAndVP");

            #line 82
            context.Mixin(mixin, "PositionVSStream");

            #line 84
            if (context.GetParam(MaterialParameters.NormalMap) != null)
            {

                #line 86
                context.Mixin(mixin, "NormalMapTexture");

                {

                    #line 87
                    var __subMixin = new ShaderMixinSourceTree() { Parent = mixin };

                    #line 87
                    context.Mixin(__subMixin, context.GetParam(MaterialParameters.NormalMap));
                    mixin.Mixin.AddComposition("normalMap", __subMixin.Mixin);
                }

                #line 88
                context.SetParam(BasicShadersParameters.UsedNormalMap, true);
            }

            #line 91
            else
            {

                #line 92
                context.Mixin(mixin, "NormalVSStream");
            }
        }

        [ModuleInitializer]
        internal static void __Initialize__()

        {
            ShaderMixinManager.Register("ParadoxBaseShader", new ParadoxBaseShader());
        }
    }
}
