// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Paradox Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Paradox.VisualStudio.Package .vsix
// and re-save the associated .pdxfx.
// </auto-generated>

using SiliconStudio.Core;
using SiliconStudio.Paradox.Effects;
using SiliconStudio.Paradox.Shaders;
using SiliconStudio.Core.Mathematics;
using SiliconStudio.Paradox.Graphics;


#line 1 "C:\Projects\Paradox\sources\shaders\DefaultDeferredEffect.pdxfx"
using SiliconStudio.Paradox.Effects.Data;

#line 2
using SiliconStudio.Paradox.Engine;

#line 4
namespace DefaultEffects
{
    [DataContract]
#line 7
    public partial class LightingParameters : ShaderMixinParameters
    {

        #line 9
        public static readonly ParameterKey<int> PerPixelDirectionalLightCount = ParameterKeys.New<int>();

        #line 10
        public static readonly ParameterKey<int> PerPixelDiffuseDirectionalLightCount = ParameterKeys.New<int>();

        #line 11
        public static readonly ParameterKey<int> PerVertexDirectionalLightCount = ParameterKeys.New<int>();

        #line 12
        public static readonly ParameterKey<int> PerVertexDiffusePixelSpecularDirectionalLightCount = ParameterKeys.New<int>();
    };

    #line 16
    public partial class ParadoxGBufferShaderPass  : IShaderMixinBuilder
    {
        public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
        {

            #line 21
            context.CloneProperties();

            #line 21
            mixin.Mixin.CloneFrom(mixin.Parent.Mixin);

            #line 22
            context.Mixin(mixin, "GBuffer");

            #line 23
            context.Mixin(mixin, "NormalVSStream");

            #line 25
            if (context.GetParam(MaterialParameters.SpecularPowerMap) != null)
            {

                #line 27
                context.Mixin(mixin, "SpecularPower");

                {

                    #line 28
                    var __subMixin = new ShaderMixinSourceTree() { Parent = mixin };

                    #line 28
                    context.Mixin(__subMixin, context.GetParam(MaterialParameters.SpecularPowerMap));
                    mixin.Mixin.AddComposition("SpecularPowerMap", __subMixin.Mixin);
                }
            }

            #line 31
            if (context.GetParam(MaterialParameters.SpecularIntensityMap) != null)
            {

                {

                    #line 33
                    var __subMixin = new ShaderMixinSourceTree() { Parent = mixin };

                    #line 33
                    context.Mixin(__subMixin, context.GetParam(MaterialParameters.SpecularIntensityMap));
                    mixin.Mixin.AddComposition("SpecularIntensityMap", __subMixin.Mixin);
                }
            }
        }

        [ModuleInitializer]
        internal static void __Initialize__()

        {
            ShaderMixinManager.Register("ParadoxGBufferShaderPass", new ParadoxGBufferShaderPass());
        }
    }

    #line 38
    public partial class ParadoxGBufferPlugin  : IShaderMixinBuilder
    {
        public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
        {

            {

                #line 40
                var __subMixin = new ShaderMixinSourceTree() { Name = "ParadoxGBufferShaderPass", Parent = mixin };
                mixin.Children.Add(__subMixin);

                #line 40
                context.BeginChild(__subMixin);

                #line 40
                context.Mixin(__subMixin, "ParadoxGBufferShaderPass");

                #line 40
                context.EndChild();
            }

            #line 43
            context.RemoveMixin(mixin, "PositionVSStream");

            #line 44
            context.RemoveMixin(mixin, "NormalVSStream");

            #line 45
            context.RemoveMixin(mixin, "SpecularPowerMap");

            #line 46
            context.RemoveMixin(mixin, "SpecularPowerPerMesh");

            #line 49
            context.Mixin(mixin, "NormalVSGBuffer");

            #line 50
            context.Mixin(mixin, "PositionVSGBuffer");

            #line 51
            context.Mixin(mixin, "SpecularPowerGBuffer");
        }

        [ModuleInitializer]
        internal static void __Initialize__()

        {
            ShaderMixinManager.Register("ParadoxGBufferPlugin", new ParadoxGBufferPlugin());
        }
    }

    #line 54
    public partial class ParadoxDeferredLightingPointGroup  : IShaderMixinBuilder
    {
        public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
        {

            #line 58
            mixin.Mixin.AddMacro("DEFERRED_MAX_POINT_LIGHT_COUNT", context.GetParam(LightingKeys.MaxDeferredLights));

            #line 60
            mixin.Mixin.AddMacro("DEFERRED_POINT_LIGHTING_UNROLL_LOOP", 1);

            #line 61
            context.Mixin(mixin, "DeferredPointLighting");
        }

        [ModuleInitializer]
        internal static void __Initialize__()

        {
            ShaderMixinManager.Register("ParadoxDeferredLightingPointGroup", new ParadoxDeferredLightingPointGroup());
        }
    }

    #line 64
    public partial class DeferredLightingDirectShadowGroup  : IShaderMixinBuilder
    {
        public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
        {

            #line 69
            mixin.Mixin.AddMacro("DEFERRED_MAX_DIRECT_SHADOW_LIGHT_COUNT", 1);

            #line 70
            mixin.Mixin.AddMacro("DEFERRED_DIRECT_LIGHTING_UNROLL_LOOP", 1);

            #line 71
            context.Mixin(mixin, "DeferredDirectionalShadowLighting");

            #line 73
            context.Mixin(mixin, "DeferredShadowMapCascadeBase");

            #line 75
            mixin.Mixin.AddMacro("SHADOWMAP_COUNT", 1);

            #line 76
            mixin.Mixin.AddMacro("SHADOWMAP_CASCADE_COUNT", context.GetParam(ShadowMapParameters.ShadowMapCascadeCount));

            #line 77
            mixin.Mixin.AddMacro("SHADOWMAP_TOTAL_COUNT", context.GetParam(ShadowMapParameters.ShadowMapCascadeCount));

            #line 78
            mixin.Mixin.AddMacro("HAS_DYNAMIC_SHADOWMAP_COUNT", 0);
        }

        [ModuleInitializer]
        internal static void __Initialize__()

        {
            ShaderMixinManager.Register("DeferredLightingDirectShadowGroup", new DeferredLightingDirectShadowGroup());
        }
    }

    #line 81
    public partial class NearestFilterGroup  : IShaderMixinBuilder
    {
        public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
        {

            #line 83
            context.Mixin(mixin, "DeferredLightingDirectShadowGroup");

            #line 84
            context.Mixin(mixin, "ShadowMapFilterDefault");
        }

        [ModuleInitializer]
        internal static void __Initialize__()

        {
            ShaderMixinManager.Register("NearestFilterGroup", new NearestFilterGroup());
        }
    }

    #line 87
    public partial class PcfGroup  : IShaderMixinBuilder
    {
        public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
        {

            #line 89
            context.Mixin(mixin, "DeferredLightingDirectShadowGroup");

            #line 90
            context.Mixin(mixin, "ShadowMapFilterPcf");
        }

        [ModuleInitializer]
        internal static void __Initialize__()

        {
            ShaderMixinManager.Register("PcfGroup", new PcfGroup());
        }
    }

    #line 93
    public partial class VsmGroup  : IShaderMixinBuilder
    {
        public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
        {

            #line 95
            context.Mixin(mixin, "DeferredLightingDirectShadowGroup");

            #line 96
            context.Mixin(mixin, "ShadowMapFilterVsm");
        }

        [ModuleInitializer]
        internal static void __Initialize__()

        {
            ShaderMixinManager.Register("VsmGroup", new VsmGroup());
        }
    }

    #line 99
    public partial class ParadoxDirectShadowPrepassLighting  : IShaderMixinBuilder
    {
        public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
        {

            #line 103
            context.CloneProperties();

            #line 103
            mixin.Mixin.CloneFrom(mixin.Parent.Mixin);

            #line 104
            context.Mixin(mixin, "DeferredShadowLightingShader");

            #line 106
            if (context.GetParam(ShadowMapParameters.FilterType) == ShadowMapFilterType.Nearest)

                {

                    #line 107
                    var __subMixin = new ShaderMixinSourceTree() { Parent = mixin };

                    #line 107
                    context.Mixin(__subMixin, "NearestFilterGroup");
                    mixin.Mixin.AddCompositionToArray("shadows", __subMixin.Mixin);
                }

            #line 108
            else 
#line 108
            if (context.GetParam(ShadowMapParameters.FilterType) == ShadowMapFilterType.PercentageCloserFiltering)

                {

                    #line 109
                    var __subMixin = new ShaderMixinSourceTree() { Parent = mixin };

                    #line 109
                    context.Mixin(__subMixin, "PcfGroup");
                    mixin.Mixin.AddCompositionToArray("shadows", __subMixin.Mixin);
                }

            #line 110
            else 
#line 110
            if (context.GetParam(ShadowMapParameters.FilterType) == ShadowMapFilterType.Variance)

                {

                    #line 111
                    var __subMixin = new ShaderMixinSourceTree() { Parent = mixin };

                    #line 111
                    context.Mixin(__subMixin, "VsmGroup");
                    mixin.Mixin.AddCompositionToArray("shadows", __subMixin.Mixin);
                }
        }

        [ModuleInitializer]
        internal static void __Initialize__()

        {
            ShaderMixinManager.Register("ParadoxDirectShadowPrepassLighting", new ParadoxDirectShadowPrepassLighting());
        }
    }

    #line 114
    public partial class ParadoxDeferredLightingDirectGroup  : IShaderMixinBuilder
    {
        public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
        {

            #line 118
            mixin.Mixin.AddMacro("DEFERRED_MAX_DIRECT_LIGHT_COUNT", 1);

            #line 119
            context.Mixin(mixin, "DeferredDirectionalLighting");
        }

        [ModuleInitializer]
        internal static void __Initialize__()

        {
            ShaderMixinManager.Register("ParadoxDeferredLightingDirectGroup", new ParadoxDeferredLightingDirectGroup());
        }
    }

    #line 122
    public partial class ParadoxDeferredLightingSpotGroup  : IShaderMixinBuilder
    {
        public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
        {

            #line 126
            mixin.Mixin.AddMacro("DEFERRED_MAX_SPOT_LIGHT_COUNT", 1);

            #line 127
            context.Mixin(mixin, "DeferredSpotLighting");
        }

        [ModuleInitializer]
        internal static void __Initialize__()

        {
            ShaderMixinManager.Register("ParadoxDeferredLightingSpotGroup", new ParadoxDeferredLightingSpotGroup());
        }
    }

    #line 130
    public partial class ParadoxDirectPrepassLighting  : IShaderMixinBuilder
    {
        public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
        {

            #line 132
            context.CloneProperties();

            #line 132
            mixin.Mixin.CloneFrom(mixin.Parent.Mixin);

            {

                #line 133
                var __subMixin = new ShaderMixinSourceTree() { Parent = mixin };

                #line 133
                context.Mixin(__subMixin, "ParadoxDeferredLightingDirectGroup");
                mixin.Mixin.AddCompositionToArray("lightingGroups", __subMixin.Mixin);
            }
        }

        [ModuleInitializer]
        internal static void __Initialize__()

        {
            ShaderMixinManager.Register("ParadoxDirectPrepassLighting", new ParadoxDirectPrepassLighting());
        }
    }

    #line 136
    public partial class ParadoxPointPrepassLighting  : IShaderMixinBuilder
    {
        public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
        {

            #line 140
            context.CloneProperties();

            #line 140
            mixin.Mixin.CloneFrom(mixin.Parent.Mixin);

            #line 141
            if (context.GetParam(LightingKeys.MaxDeferredLights) > 0)

                {

                    #line 142
                    var __subMixin = new ShaderMixinSourceTree() { Parent = mixin };

                    #line 142
                    context.Mixin(__subMixin, "ParadoxDeferredLightingPointGroup");
                    mixin.Mixin.AddCompositionToArray("lightingGroups", __subMixin.Mixin);
                }
        }

        [ModuleInitializer]
        internal static void __Initialize__()

        {
            ShaderMixinManager.Register("ParadoxPointPrepassLighting", new ParadoxPointPrepassLighting());
        }
    }

    #line 145
    public partial class ParadoxSpotPrepassLighting  : IShaderMixinBuilder
    {
        public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
        {

            #line 149
            context.CloneProperties();

            #line 149
            mixin.Mixin.CloneFrom(mixin.Parent.Mixin);

            {

                #line 150
                var __subMixin = new ShaderMixinSourceTree() { Parent = mixin };

                #line 150
                context.Mixin(__subMixin, "ParadoxDeferredLightingSpotGroup");
                mixin.Mixin.AddCompositionToArray("lightingGroups", __subMixin.Mixin);
            }
        }

        [ModuleInitializer]
        internal static void __Initialize__()

        {
            ShaderMixinManager.Register("ParadoxSpotPrepassLighting", new ParadoxSpotPrepassLighting());
        }
    }

    #line 153
    public partial class ParadoxDeferredSpecular  : IShaderMixinBuilder
    {
        public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
        {

            #line 155
            context.Mixin(mixin, "ComputeBRDFColorSpecularBlinnPhong");

            #line 156
            context.Mixin(mixin, "SpecularPowerGBuffer");

            {

                #line 157
                var __subMixin = new ShaderMixinSourceTree() { Parent = mixin };

                #line 157
                context.Mixin(__subMixin, "ComputeColorOne");
                mixin.Mixin.AddComposition("SpecularIntensityMap", __subMixin.Mixin);
            }
        }

        [ModuleInitializer]
        internal static void __Initialize__()

        {
            ShaderMixinManager.Register("ParadoxDeferredSpecular", new ParadoxDeferredSpecular());
        }
    }

    #line 160
    public partial class ParadoxDefaultLightPrepassEffect  : IShaderMixinBuilder
    {
        public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
        {

            #line 164
            context.Mixin(mixin, "PositionVSGBuffer");

            #line 165
            context.Mixin(mixin, "NormalVSGBuffer");

            #line 166
            context.Mixin(mixin, "BRDFDiffuseBase");

            #line 167
            context.Mixin(mixin, "BRDFSpecularBase");

            {

                #line 168
                var __subMixin = new ShaderMixinSourceTree() { Parent = mixin };

                #line 168
                context.Mixin(__subMixin, "ComputeBRDFColorFresnel");
                mixin.Mixin.AddComposition("DiffuseColor", __subMixin.Mixin);
            }

            {

                #line 169
                var __subMixin = new ShaderMixinSourceTree() { Parent = mixin };

                #line 169
                context.Mixin(__subMixin, "ComputeBRDFDiffuseLambert");
                mixin.Mixin.AddComposition("DiffuseLighting", __subMixin.Mixin);
            }

            {

                #line 170
                var __subMixin = new ShaderMixinSourceTree() { Parent = mixin };

                #line 170
                context.Mixin(__subMixin, "ComputeBRDFColor");
                mixin.Mixin.AddComposition("SpecularColor", __subMixin.Mixin);
            }

            {

                #line 171
                var __subMixin = new ShaderMixinSourceTree() { Parent = mixin };

                #line 171
                context.Mixin(__subMixin, "ParadoxDeferredSpecular");
                mixin.Mixin.AddComposition("SpecularLighting", __subMixin.Mixin);
            }

            {

                #line 173
                var __subMixin = new ShaderMixinSourceTree() { Name = "ParadoxDirectShadowPrepassLighting", Parent = mixin };
                mixin.Children.Add(__subMixin);

                #line 173
                context.BeginChild(__subMixin);

                #line 173
                context.Mixin(__subMixin, "ParadoxDirectShadowPrepassLighting");

                #line 173
                context.EndChild();
            }

            #line 175
            context.Mixin(mixin, "DeferredLightingShader");

            {

                #line 177
                var __subMixin = new ShaderMixinSourceTree() { Name = "ParadoxDirectPrepassLighting", Parent = mixin };
                mixin.Children.Add(__subMixin);

                #line 177
                context.BeginChild(__subMixin);

                #line 177
                context.Mixin(__subMixin, "ParadoxDirectPrepassLighting");

                #line 177
                context.EndChild();
            }

            {

                #line 179
                var __subMixin = new ShaderMixinSourceTree() { Name = "ParadoxSpotPrepassLighting", Parent = mixin };
                mixin.Children.Add(__subMixin);

                #line 179
                context.BeginChild(__subMixin);

                #line 179
                context.Mixin(__subMixin, "ParadoxSpotPrepassLighting");

                #line 179
                context.EndChild();
            }

            {

                #line 181
                var __subMixin = new ShaderMixinSourceTree() { Name = "ParadoxPointPrepassLighting", Parent = mixin };
                mixin.Children.Add(__subMixin);

                #line 181
                context.BeginChild(__subMixin);

                #line 181
                context.Mixin(__subMixin, "ParadoxPointPrepassLighting");

                #line 181
                context.EndChild();
            }
        }

        [ModuleInitializer]
        internal static void __Initialize__()

        {
            ShaderMixinManager.Register("ParadoxDefaultLightPrepassEffect", new ParadoxDefaultLightPrepassEffect());
        }
    }

    #line 184
    public partial class DirectionalLightsShader  : IShaderMixinBuilder
    {
        public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
        {

            #line 189
            mixin.Mixin.AddMacro("LIGHTING_MAX_LIGHT_COUNT", context.GetParam(LightingKeys.MaxDirectionalLights));

            #line 190
            if (context.GetParam(LightingKeys.UnrollDirectionalLightLoop))

                #line 191
                mixin.Mixin.AddMacro("LIGHTING_UNROLL_LOOP", true);

            #line 193
            if (context.GetParam(MaterialParameters.LightingType) == MaterialLightingType.DiffusePixel)
            {

                #line 195
                context.Mixin(mixin, "ShadingDiffusePerPixel");
            }

            #line 197
            else 
#line 197
            if (context.GetParam(MaterialParameters.LightingType) == MaterialLightingType.DiffuseVertex)
            {

                #line 199
                context.Mixin(mixin, "ShadingDiffusePerVertex");
            }

            #line 201
            else 
#line 201
            if (context.GetParam(MaterialParameters.LightingType) == MaterialLightingType.DiffuseSpecularPixel)
            {

                #line 203
                context.Mixin(mixin, "ShadingDiffuseSpecularPerPixel");
            }

            #line 205
            else 
#line 205
            if (context.GetParam(MaterialParameters.LightingType) == MaterialLightingType.DiffuseVertexSpecularPixel)
            {

                #line 207
                context.Mixin(mixin, "ShadingDiffusePerVertexSpecularPerPixel");
            }

            #line 209
            context.Mixin(mixin, "DirectionalShading");

            #line 210
            context.Mixin(mixin, "ShadingEyeNormalVS");
        }

        [ModuleInitializer]
        internal static void __Initialize__()

        {
            ShaderMixinManager.Register("DirectionalLightsShader", new DirectionalLightsShader());
        }
    }

    #line 213
    public partial class ParadoxDiffuseDeferred  : IShaderMixinBuilder
    {
        public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
        {

            #line 217
            if (context.GetParam(MaterialParameters.AlbedoDiffuse) != null)
            {

                {

                    #line 219
                    var __subMixin = new ShaderMixinSourceTree() { Parent = mixin };

                    #line 219
                    context.Mixin(__subMixin, context.GetParam(MaterialParameters.AlbedoDiffuse));
                    mixin.Mixin.AddComposition("albedoDiffuse", __subMixin.Mixin);
                }
            }
        }

        [ModuleInitializer]
        internal static void __Initialize__()

        {
            ShaderMixinManager.Register("ParadoxDiffuseDeferred", new ParadoxDiffuseDeferred());
        }
    }

    #line 223
    public partial class ParadoxSpecularDeferred  : IShaderMixinBuilder
    {
        public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
        {

            #line 227
            if (context.GetParam(MaterialParameters.AlbedoSpecular) != null)
            {

                {

                    #line 229
                    var __subMixin = new ShaderMixinSourceTree() { Parent = mixin };

                    #line 229
                    context.Mixin(__subMixin, context.GetParam(MaterialParameters.AlbedoSpecular));
                    mixin.Mixin.AddComposition("albedoSpecular", __subMixin.Mixin);
                }
            }
        }

        [ModuleInitializer]
        internal static void __Initialize__()

        {
            ShaderMixinManager.Register("ParadoxSpecularDeferred", new ParadoxSpecularDeferred());
        }
    }

    #line 233
    public partial class ParadoxDefaultDeferredShader  : IShaderMixinBuilder
    {
        public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
        {

            #line 238
            context.Mixin(mixin, "ParadoxBaseShader");

            #line 240
            context.Mixin(mixin, "ParadoxSkinning");

            #line 242
            context.Mixin(mixin, "ParadoxShadowCast");

            #line 246
            if (context.GetParam(RenderingParameters.UseDeferred) && !context.GetParam(MaterialParameters.UseTransparent))
            {

                #line 248
                context.Mixin(mixin, "ParadoxGBufferPlugin");

                #line 249
                context.Mixin(mixin, "LightDeferredShading");

                #line 250
                context.Mixin(mixin, "ParadoxDiffuseDeferred");

                #line 251
                context.Mixin(mixin, "ParadoxSpecularDeferred");

                #line 253
                if (context.GetParam(MaterialParameters.AmbientMap) != null)
                {

                    #line 255
                    context.Mixin(mixin, "AmbientMapShading");

                    {

                        #line 256
                        var __subMixin = new ShaderMixinSourceTree() { Parent = mixin };

                        #line 256
                        context.Mixin(__subMixin, context.GetParam(MaterialParameters.AmbientMap));
                        mixin.Mixin.AddComposition("AmbientMap", __subMixin.Mixin);
                    }
                }
            }

            #line 260
            else
            {

                #line 261
                context.Mixin(mixin, "ParadoxDiffuseForward");

                #line 262
                context.Mixin(mixin, "ParadoxSpecularForward");

                #line 264
                if (context.GetParam(MaterialParameters.AmbientMap) != null)
                {

                    #line 266
                    context.Mixin(mixin, "AmbientMapShading");

                    {

                        #line 267
                        var __subMixin = new ShaderMixinSourceTree() { Parent = mixin };

                        #line 267
                        context.Mixin(__subMixin, context.GetParam(MaterialParameters.AmbientMap));
                        mixin.Mixin.AddComposition("AmbientMap", __subMixin.Mixin);
                    }
                }

                #line 270
                if (context.GetParam(MaterialParameters.UseTransparent))
                {

                    #line 272
                    context.Mixin(mixin, "TransparentShading");

                    #line 273
                    context.Mixin(mixin, "DiscardTransparent");
                }
            }
        }

        [ModuleInitializer]
        internal static void __Initialize__()

        {
            ShaderMixinManager.Register("ParadoxDefaultDeferredShader", new ParadoxDefaultDeferredShader());
        }
    }
}
