// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Paradox Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Paradox.VisualStudio.Package .vsix
// and re-save the associated .pdxfx.
// </auto-generated>

using System;
using SiliconStudio.Core;
using SiliconStudio.Paradox.Effects;
using SiliconStudio.Paradox.Graphics;
using SiliconStudio.Paradox.Shaders;
using SiliconStudio.Core.Mathematics;
using Buffer = SiliconStudio.Paradox.Graphics.Buffer;


#line 3 "D:\Code\Paradox\sources\shaders\Images\GaussianBlur\GaussianBlurEffect.pdxfx"
namespace SiliconStudio.Paradox.Effects.Images
{

    #line 5
    internal static partial class ShaderMixins
    {
        internal partial class GaussianBlurEffect  : IShaderMixinBuilderExtended
        {
            public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
            {

                #line 9

                #line 9
                var blur = GaussianUtil.GetBlurMacros(context.GetParam(GaussianBlur.RadiusKey), !context.GetParam(GaussianBlur.UseSigma3Key));

                #line 11
                mixin.Mixin.AddMacro("BLUR_COUNT", blur.Count);

                #line 12
                mixin.Mixin.AddMacro("BLUR_OFFSETS", blur.Offsets);

                #line 13
                mixin.Mixin.AddMacro("BLUR_WEIGHTS", blur.Weights);

                #line 14
                mixin.Mixin.AddMacro("BLUR_DIRECTION", context.GetParam(GaussianBlur.VerticalBlurKey) ? "float2(0,1)" : "float2(1,0)");

                #line 15
                context.Mixin(mixin, "GaussianBlurShader");
            }
            private readonly ParameterKey[] __keys__ = new ParameterKey[]
            {
                GaussianBlur.RadiusKey,
                GaussianBlur.UseSigma3Key,
                GaussianBlur.VerticalBlurKey,
            };
            public ParameterKey[] Keys
            {
                get
                {
                    return __keys__;
                }
            }
            private readonly string[] __mixins__ = new string[]
            {
                "GaussianBlurShader",
            };
            public string[] Mixins
            {
                get
                {
                    return __mixins__;
                }
            }

            [ModuleInitializer]
            internal static void __Initialize__()

            {
                ShaderMixinManager.Register("GaussianBlurEffect", new GaussianBlurEffect());
            }
        }
    }
}
