// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using SiliconStudio.Core;
using SiliconStudio.Xenko.Rendering;
using SiliconStudio.Xenko.Graphics;
using SiliconStudio.Xenko.Shaders;
using SiliconStudio.Core.Mathematics;
using Buffer = SiliconStudio.Xenko.Graphics.Buffer;

namespace SiliconStudio.Xenko.Rendering.Images
{
    internal static partial class FlareArtifactShaderKeys
    {
        public static readonly ParameterKey<float> Amount = ParameterKeys.New<float>();
        public static readonly ParameterKey<Vector2> ZoomOffsetsDistortions = ParameterKeys.New<Vector2>();
        public static readonly ParameterKey<Vector3> ColorAberrations = ParameterKeys.New<Vector3>();
        public static readonly ParameterKey<float> AberrationStrength = ParameterKeys.New<float>(0);
    }
}
