// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using SiliconStudio.Core;
using SiliconStudio.Xenko.Rendering;
using SiliconStudio.Xenko.Graphics;
using SiliconStudio.Xenko.Shaders;
using SiliconStudio.Core.Mathematics;
using Buffer = SiliconStudio.Xenko.Graphics.Buffer;

namespace SiliconStudio.Xenko.Rendering.Images
{
    public static partial class SSLRCommonKeys
    {
        public static readonly ValueParameterKey<float> MaxColorMiplevel = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> TraceSizeMax = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<Vector2> TexelSize = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<Vector2> SSRtexelSize = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<float> RoughnessFade = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> MaxTraceSamples = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> UseTemporal = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> TemporalResponse = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> TemporalScale = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> Padding0 = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> Time = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> BRDFBias = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<Vector2> Padding1 = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<float> ViewFarPlane = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> RayStepScale = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<Vector2> ScreenSize = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<Vector4> ViewInfo = ParameterKeys.NewValue<Vector4>();
        public static readonly ValueParameterKey<Vector4> CameraPosWS = ParameterKeys.NewValue<Vector4>();
        public static readonly ValueParameterKey<Matrix> V = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Matrix> VP = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Matrix> IVP = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Matrix> P = ParameterKeys.NewValue<Matrix>();
    }
}
