// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using SiliconStudio.Core;
using SiliconStudio.Xenko.Rendering;
using SiliconStudio.Xenko.Graphics;
using SiliconStudio.Xenko.Shaders;
using SiliconStudio.Core.Mathematics;
using Buffer = SiliconStudio.Xenko.Graphics.Buffer;

namespace SiliconStudio.Xenko.Rendering
{
    public static partial class ParticleUtilitiesKeys
    {
        public static readonly ValueParameterKey<Matrix> ViewMatrix = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Matrix> ProjectionMatrix = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Matrix> ViewProjectionMatrix = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Vector4> ViewFrustum = ParameterKeys.NewValue<Vector4>();
    }
}
